apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-deploy
  labels:
    app: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm
  template:
    metadata:
      labels:
        app: helm
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: helm-pod
        image: vishnu981824/app1
        imagePullPolicy: Always
        ports:
        - containerPort: 8082